spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/pass}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: ${JWT_KEY:ts5r/cjd7FasOcNkwdwh5iy70LDT65PY2b/J56j5+5Y=}
  access-token-expiration: 14400000